// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Media {
    "type": MediaType;
    "url"?: string;
    "pageUrl": string;
    "thumbnailUrl"?: string;
    "name"?: string;
    "size"?: string;
}

export enum MediaType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MediaTypeImage = "image",
    MediaTypeVideo = "video",
    MediaTypeFile = "file",
    MediaTypeUnknown = "unknown",
};
