// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Photo {
    /**
     * Creates a new Photo instance.
     * @param {Partial<Photo>} [$$source = {}] - The source object to create the Photo.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["thumbnailUrl"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Photo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Photo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Photo(/** @type {Partial<Photo>} */($$parsedSource));
    }
}
