// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Media {
    /**
     * Creates a new Media instance.
     * @param {Partial<Media>} [$$source = {}] - The source object to create the Media.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {MediaType}
             */
            this["type"] = MediaType.$zero;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["thumbnailUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["size"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Media instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Media}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Media(/** @type {Partial<Media>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const MediaType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MediaTypeImage: "image",
    MediaTypeVideo: "video",
    MediaTypeFile: "file",
    MediaTypeUnknown: "unknown",
};
