version: "2"

linters:
  default: all
  disable:
    - gomodguard
    - depguard
    - err113
    - exhaustruct
    - mnd
    - wrapcheck
    - forbidigo
    - revive
    - wsl
    - funlen
    - dupl
    - lll
  settings:
    varnamelen:
      ignore-decls:
        - c *colly.Collector
        - i int
        - wg sync.WaitGroup
        - e *colly.HTMLElement
  exclusions:
    paths:
      - "assets/"
      - "task/"
      - "bin/"
      - "build/"
      - "frontend/"
