version: "2"

linters:
  default: all
  disable:
    - gomodguard
    - depguard
    - err113
    - exhaustruct
    - mnd
    - wrapcheck
    - forbidigo
    - revive
    - wsl
    - funlen
    - dupl
    - lll
    - noinlineerr
  settings:
    varnamelen:
      ignore-decls:
        - c *colly.Collector
        - i int
        - wg sync.WaitGroup
        - e *colly.HTMLElement
        - gh *github.Provider
        - mu sync.Mutex
        - mu sync.RWMutex
        - t *time.Timer
  exclusions:
    paths:
      - "assets/"
      - "task/"
      - "bin/"
      - "build/"
      - "frontend/"
    rules:
      - path: _test\.go
        linters:
          - goconst
