version: "2"

issues:
  exclude-dirs:
    - build/
    - assets/
    - frontend/

linters:
  default: all
  disable: 
    - depguard
    - err113
    - exhaustruct
    - mnd
    - wrapcheck
    - forbidigo
    - revive

linters-settings:
  varnamelen:
    ignore-decls:
      - c *colly.Collector
      - i int
      - wg sync.WaitGroup
