issues:
  exclude-dirs:
    - build/
    - assets/
    - frontend/

linters:
  enable-all: true
  disable:
    - dupl
    - exhaustruct
    - mnd
    - depguard
    - wrapcheck
    - forbidigo
    - err113
    - usestdlibvars
    - paralleltest
    - ireturn # TODO: fix
    - gomnd # Deprecated
    - exportloopref # Deprecated
    - execinquery # Deprecated

linters-settings:
  varnamelen:
    ignore-decls:
      - c *colly.Collector
      - i int
