// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as providers$0 from "./internal/providers/models.js";

/**
 * @param {string} src
 * @param {string} collectionInput
 * @param {string} providerName
 * @returns {$CancellablePromise<void>}
 */
export function DownloadPhoto(src, collectionInput, providerName) {
    return $Call.ByID(1585192130, src, collectionInput, providerName);
}

/**
 * @param {string} collectionInput
 * @param {string} providerName
 * @param {number} maxParallelDownloads
 * @returns {$CancellablePromise<void>}
 */
export function DownloadPhotos(collectionInput, providerName, maxParallelDownloads) {
    return $Call.ByID(1851861667, collectionInput, providerName, maxParallelDownloads);
}

/**
 * @returns {$CancellablePromise<config$0.DownloadDir>}
 */
export function GetDownloadDir() {
    return $Call.ByID(584523237).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} collectionInput
 * @param {string} providerName
 * @returns {$CancellablePromise<providers$0.Photo[]>}
 */
export function GetPhotos(collectionInput, providerName) {
    return $Call.ByID(3978296423, collectionInput, providerName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.DownloadDir | null>}
 */
export function SelectDownloadDir() {
    return $Call.ByID(446453289).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopTask() {
    return $Call.ByID(2085242431);
}

/**
 * @returns {$CancellablePromise<config$0.DownloadDir | null>}
 */
export function UnsetDownloadDir() {
    return $Call.ByID(1426826490).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = config$0.DownloadDir.createFrom;
const $$createType1 = providers$0.Photo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Nullable($$createType0);
