// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as providers$0 from "./internal/providers/models.js";

export function DownloadMedia(pageURL: string, collectionInput: string, providerName: string): $CancellablePromise<void> {
    return $Call.ByID(1565500426, pageURL, collectionInput, providerName);
}

export function DownloadMediaItems(collectionInput: string, providerName: string, maxParallelDownloads: number): $CancellablePromise<void> {
    return $Call.ByID(2935682774, collectionInput, providerName, maxParallelDownloads);
}

export function GetDownloadDir(): $CancellablePromise<config$0.DownloadDir> {
    return $Call.ByID(584523237);
}

export function GetMediaItems(collectionInput: string, providerName: string): $CancellablePromise<providers$0.Media[] | null> {
    return $Call.ByID(2981449778, collectionInput, providerName);
}

export function SelectDownloadDir(): $CancellablePromise<config$0.DownloadDir | null> {
    return $Call.ByID(446453289);
}

export function StopTask(): $CancellablePromise<void> {
    return $Call.ByID(2085242431);
}

export function UnsetDownloadDir(): $CancellablePromise<config$0.DownloadDir | null> {
    return $Call.ByID(1426826490);
}
