// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";

export function Check(): $CancellablePromise<void> {
    return $Call.ByID(688929688);
}

export function GetUpdatesConfig(): $CancellablePromise<config$0.Updates> {
    return $Call.ByID(3663123460);
}

export function SetUpdatesConfig(updates: config$0.Updates): $CancellablePromise<config$0.Updates> {
    return $Call.ByID(2627596160, updates);
}
