// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum CheckInterval {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    IntervalDay = 1440,
    Interval3Days = 4320,
    IntervalWeek = 10080,
    IntervalMonth = 43200,

    defaultCheckIntervalMinutes = 10080,
};

export interface DownloadDir {
    "path": string;
    "isDefault": boolean;
}

export interface Updates {
    "autoCheck": boolean;
    "checkOnStartup": boolean;
    "checkIntervalMinutes": CheckInterval;
    "includePrereleases": boolean;
    "lastCheckedAt": string | null;
}
