// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DownloadDir {
    /**
     * Creates a new DownloadDir instance.
     * @param {Partial<DownloadDir>} [$$source = {}] - The source object to create the DownloadDir.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDefault" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadDir instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadDir}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadDir(/** @type {Partial<DownloadDir>} */($$parsedSource));
    }
}
