// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadPhotos(arg1, arg2) {
  return window['go']['main']['App']['DownloadPhotos'](arg1, arg2);
}

export function GetPhotos(arg1, arg2) {
  return window['go']['main']['App']['GetPhotos'](arg1, arg2);
}
