// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadPhotos(arg1:string,arg2:string):Promise<void>;

export function GetPhotos(arg1:string,arg2:string):Promise<Array<string>>;

export function StopTask():Promise<void>;
