name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  release:
    strategy:
      matrix:
        build:
          [
            { name: Fapesnap, platform: linux/amd64, os: ubuntu-latest },
            { name: Fapesnap, platform: windows/amd64, os: windows-latest },
            { name: Fapesnap, platform: darwin/universal, os: macos-latest },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: 1.23
          node-version: 20
