name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            goos: linux
            goarch: amd64
            artifact: fapesnap-linux-amd64.tar.gz
          - os: macos-latest
            goos: darwin
            goarch: arm64
            artifact: fapesnap-macos-arm64.app.zip
          - os: windows-latest
            goos: windows
            goarch: amd64
            artifact: fapesnap-windows-amd64.exe
          - os: windows-latest
            goos: windows
            goarch: arm64
            artifact: fapesnap-windows-arm64.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install linux dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        if: matrix.goos == 'linux'
        with:
          packages: build-essential pkg-config libgtk-4-dev libwebkitgtk-6.0-dev
          version: 1.0

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest

      - name: Install Task
        uses: go-task/setup-task@v2

      - name: Build
        run: wails3 build GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }}

      - name: Package binaries
        if: matrix.goos == 'darwin'
        run: wails3 package

      - name: Archive assets
        shell: bash
        run: |
          if [ "${{ matrix.goos }}" == "linux" ]; then
            tar -czf ${{ matrix.artifact }} -C bin/ fapesnap
          elif [ "${{ matrix.goos }}" == "darwin" ]; then
            zip -ry ${{ matrix.artifact }} bin/fapesnap.app
          else
            cp bin/fapesnap.exe ${{ matrix.artifact }}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Generate Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: HYBRID
          configurationJson: |
            {
              "commit_template": "- #{{MERGE_SHA}} #{{TITLE}}",
              "categories": [
                {
                    "title": "## ✨ Features",
                    "labels": ["feat", "feature"]
                },
                {
                    "title": "## 🔧 Fixes",
                    "labels": ["fix", "bug"]
                },
                {
                    "title": "## 📦 Other",
                    "labels": []
                }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "on_property": "title",
                  "target": "$1"
                }
              ]
            }

      - name: Update release (Update the release created by wails-build-action)
        uses: softprops/action-gh-release@v3
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          files: artifacts/**/*
