// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadPhoto(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadPhoto'](arg1, arg2, arg3);
}

export function DownloadPhotos(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadPhotos'](arg1, arg2, arg3);
}

export function GetPhotos(arg1, arg2) {
  return window['go']['main']['App']['GetPhotos'](arg1, arg2);
}

export function StopTask() {
  return window['go']['main']['App']['StopTask']();
}
