// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {providers} from '../models';

export function DownloadPhoto(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadPhotos(arg1:string,arg2:string,arg3:number):Promise<void>;

export function GetPhotos(arg1:string,arg2:string):Promise<Array<providers.Photo>>;

export function StopTask():Promise<void>;
